site_name: IHC - Grupo 02
site_url: https://Interacao-Humano-Computador.github.io/2026.1-Grupo02
repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo02
repo_name: 2026.1-Grupo02

plugins:
    - search
    - mermaid2

theme:
  name: material
  language: pt
  logo: img/site_logo.png
  favicon: img/site_logo.png
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

nav:
  - Inicio: index.md
  - Planejamento:
      - Cronograma: Planejamento/cronograma.md
      - Heatmap: Planejamento/heatmap.md
      - Ferramentas: Planejamento/ferramentas.md
      - Processo de Design: Planejamento/Processo_Design.md
      - Sites Analisados: Planejamento/sites_analisados.md
      - Site Selecionado: Planejamento/site_selecionado.md
      - Reunioes:
          - Ata 09/04/26: Reunioes/Ata Reunião 09 04 26.md
          - Ata 11/04/26: Reunioes/Ata Reunião 11 04 26.md
          - Ata 23/04/26: Reunioes/Ata Reunião 23 04 26.md
          - Ata 30/04/26: Reunioes/Ata Reunião 30 04 26.md
  - Análise de Requisitos:
      - Perfil de Usuário: Analise de Requisitos/PerfilDeUsuario.md
      - Cenários:
        - Cenário 1: Analise de Requisitos/Cenario/cenario_agendamento.md
        - Cenário 2: Analise de Requisitos/Cenario/cenario_LucasFerreira.md
        - Cenário 3: Analise de Requisitos/Cenario/cenario_RafaelMendonca.md
        - Cenário 4: Analise de Requisitos/Cenario/cenario_mesario.md
        - Cenário 5: Analise de Requisitos/Cenario/cenario_alterarlocaldevotacao.md
        - Cenário 6: Analise de Requisitos/Cenario/cenario_certidaoquitacaoeleitoral.md
        - Cenário 7: Analise de Requisitos/Cenario/cenario_emissao_1.md
      - Personas:
        - Persona 1: Analise de Requisitos/Personas/persona_LucasMendes.md
        - Persona 3: Analise de Requisitos/Personas/persona_RafaelMendonca.md
        - Persona 4: Analise de Requisitos/Personas/persona_karina.md
        - Persona 5: Analise de Requisitos/Personas/persona_FelixRyan.md
        - Persona 6: Analise de Requisitos/Personas/persona_fernanda.md
        - Persona 7: Analise de Requisitos/Personas/Persona_LucasFerreira.md
        - Persona 8: Analise de Requisitos/Personas/persona_luiz.md
        - Persona 9: Analise de Requisitos/Personas/persona_Tamara.md
      - Análise de Tarefas:
        - Análise de Tarefas do comparativo de candidatos: Analise de Requisitos/Analise de Tarefas/ComparativoCandidatos.md
        - Análise de Tarefas do agendamento presencial: Analise de Requisitos/Analise de Tarefas/AgendamentoPresencial.md
        - Análise de Tarefas para se voluntariar a mesário: Analise de Requisitos/Analise de Tarefas/Mesario.md
        - Análise de Tarefas para alterar local de votação: Analise de Requisitos/Analise de Tarefas/AlterarLocalVotacao.md
        - Análise de Tarefas para certidão de quitação eleitoral: Analise de Requisitos/Analise de Tarefas/CertidaoQuitacaoEleitoral.md
        - Análise de Tarefas para emissão de 1º título de eleitor: Analise de Requisitos/Analise de Tarefas/Emissao1Titulo.md
      - Verificação:
          - Etapa 1: Avaliacao/avaliacao.md
          - Etapa 2: Avaliacao/Lista_de_Verificação_Entrega2.md
        
        
